name: Test

on:
  push:
    paths-ignore:
      - 'README.md'
    tags-ignore:
      - 'v*'
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Tidy
        run: go mod tidy
      - name: Download
        run: go mod download
      - name: Vet
        run: go vet ./...